version: 2.1
jobs:
  run_tests:
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          comand: |
            npm install --save

      - run:
        name: Run unit tests
        command: |
          ./node_modules/mocha/bin/mocha test --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
        path: test-results
      - store_artifacts:
        path: test-results
workflows:
  build_test:
    jobs:
      - run_tests
